name:                SIGES
version:             0.1.0.0
github:              "franklingg/SIGES"
license:             BSD3
author:              "Franklin Regis"
maintainer:          "franklin.oliveira@ccc.ufcg.edu.br"
copyright:           "2021 Franklin Regis"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/franklingg/SIGES#readme>

dependencies:
- base >= 4.7 && < 5
- containers
- bytestring
- email-validate
- haskeline
- password
- text
- aeson
- time
- ansi-terminal
- process
- directory
- split
- monad-loops
- cond

library:
  source-dirs: src

executables:
  SIGES-exe:
    main:                Main.hs
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SIGES

tests:
  SIGES-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - SIGES
    - hspec
